#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:10:00 
#SBATCH -J BL_Size_Test_job 
#SBATCH -o MyBlockedOutputFile.%j.out
#SBATCH -e MyBlockedErrorFile.%j.err


srun -n 1 -N 1 --cpu-freq=2400000 ./test-block-sizes
